Add licensing info, bump version to 2.2.10, fix exits, fix 64-bits build

diff --git a/libsigc++.SlackBuild b/libsigc++.SlackBuild
--- a/libsigc++.SlackBuild
+++ b/libsigc++.SlackBuild
@@ -1,14 +1,30 @@
 #!/bin/sh
 #
-# SlackBuild for LibSigC++
-# Written by Georgi D. Sotirov <gdsotirov@dir.bg>
+# Slackware build script for LibSigC++
+# Copyright (C) 2007-2012 Georgi D. Sotirov <gdsotirov@dir.bg>
+#
+# This program is free software; you can redistribute it and/or
+# modify it under the terms of the GNU General Public License
+# as published by the Free Software Foundation; either version 2
+# of the License, or (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program; if not, write to the Free Software
+# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
+# 
+# $Id: libsigc++.SlackBuild,v 1.7 2012/01/02 16:52:59 gsotirov Exp $
 #
 
-. ../slack-package.conf
+. ../../slack-package.conf
 
 NAME=libsigc++
-VERSION=2.2.8
-BUILD=1
+VERSION=2.2.10
+BUILD=${BUILD:-1}
 
 TMP=${TMP:-/tmp}
 CWD=${CWD:-`pwd`}
@@ -33,7 +49,7 @@ mkdir -p $PKG
 
 # Extract source
 cd $TMP
-tar -jxvf $CWD/$NAME-$VERSION.tar.bz2
+tar -xvf $CWD/$NAME-$VERSION.tar.bz2 || exit 3
 cd $SRC
 fix_source
 
@@ -43,14 +59,16 @@ CXXFLAGS=$SLKCFLAGS \
 ./configure --build=$ARCH-slackware-linux \
             --host=$ARCH-slackware-linux \
             --prefix=/usr \
+	    --libdir=/usr/lib${LIBDIRSUFFIX} \
             --docdir=/usr/doc/$NAME-$VERSION \
 	    --enable-shared=yes \
-	    --enable-static=no || exit 1
+	    --enable-static=no || exit 4
 
 # Build & install
-make -j4 || exit 2
-make DESTDIR=$PKG install || exit 3
+make -j4 || exit 5
+make DESTDIR=$PKG install || exit 6
 
+# Prepare
 ( cd $PKG; strip_lib )
 ( cd $SRC; create_docs $PKG $NAME-$VERSION )
 
@@ -63,6 +81,7 @@ install -m 644 $CWD/slack-desc       $PKG/usr/src/slackbuilds/$NAME-$VERSION/sla
 install -m 644 $CWD/slack-required   $PKG/usr/src/slackbuilds/$NAME-$VERSION/slack-required
 install -m 644 $CWD/$NAME.SlackBuild $PKG/usr/src/slackbuilds/$NAME-$VERSION/$NAME.SlackBuild
 
+# Assemble
 cd $PKG
 PKGNAME=$NAME-$VERSION-$ARCH-$BUILD$MYIN
 makepkg -l y -c n $PKG_DIR/$PKGNAME.txz
@@ -70,6 +89,7 @@ cd $PKG_DIR
 md5sum $PKGNAME.txz > $PKGNAME.txz.md5
 cat $PKG/install/slack-desc > $PKG_DIR/$PKGNAME.txt
 
+# Clean up (optionally)
 if [ "$1" == "--cleanup" ]; then
   rm -r $SRC
   rm -r $PKG
